version: '3.9'
services:
  frontend:
    image: jobzfront
    container_name: frontend
    command: npm start
    working_dir: /app
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
        - '.:/app'
        - '/app/node_modules'
    ports:
        - '3000:3000'
    