version: '3.9'
services:
  db:
    image: postgres
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - postgres.env
    ports:
      - "5432:5432"
    networks:
      JobzNetwork:
        ipv4_address: 172.20.0.2
  backend:
    image: antonioaldisio/jobzbackend
    container_name: backend
    working_dir: /code/jobz
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - postgres.env
    networks:
      - JobzNetwork
    depends_on:
      - db

  frontend:
    image: antonioaldisio/jobzfrontend
    container_name: frontend
    working_dir: /app
    command: npm start
    ports:
      - '3000:3000'
    depends_on:
      - backend
networks:
  JobzNetwork:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.1/16
         gateway: 172.20.0.1
